### ISSUE TITLE
terraform plan fails

### ISSUE THREAD

**Issue by I-Would-Like-To-Report-A-Bug-Please** [serialt/terraform-provider-nexus#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### Nexus Provider Version

2.5.0

### Nexus  Version

3.70.2-01

### Affected Resource(s)/Data Source(s)

nexus_blobstore_group

### Terraform Configuration Files

```HCL
resource "nexus_blobstore_group" "it-releases" {
  fill_policy = "writeToFirst"
  members     = [
    nexus_blobstore_s3.s3_it_releases.name,
  ]
  name        = "it-releases"
}
```

### Debug Output/Panic Output

```shell
nexus_blobstore_group.it-releases: Refreshing state... [id=it-releases]
╷
│ Error: Plugin did not respond
│ 
│   with nexus_blobstore_group.it-releases,
│   on nexus_blobstore.tf line 9, in resource "nexus_blobstore_group" "it-releases":
│    9: resource "nexus_blobstore_group" "it-releases" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
╷
│ Error: Request cancelled
│ 
│   with nexus_repository_maven_group.pp-maven2,
│   on nexus_repository.tf line 181, in resource "nexus_repository_maven_group" "pp-maven2":
│  181: resource "nexus_repository_maven_group" "pp-maven2" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

...
<bunch of plugin did not respond or request cancelled errors for multiple repositories>
...
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-nexus_v2.5.0 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "9223372036854776000": value out of range

goroutine 1044 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc000598380, {0xc000841210, 0x1, 0x1}, 0x8?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:556 +0x319
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0xc000598380)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:354 +0x473
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0xc0003afb20, {{{0xe8c038?, 0xc00009c050?}}, {0xc4d420?, 0xc00028f110?}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:698 +0x1d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00039e8b8, {0xe8c070?, 0xc00028eb10?}, 0xc000616240)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:682 +0x41d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000251180, {0xe8c070?, 0xc00028e270?}, 0xc000aa8000)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x309
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd29920, 0xc000251180}, {0xe8c070, 0xc00028e270}, 0xc000598000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001a6e00, {0xe8c070, 0xc00028e1e0}, {0xe90a60, 0xc000488000}, 0xc0001e6000, 0xc0003b9620, 0x1416f88, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xe1a
google.golang.org/grpc.(*Server).handleStream(0xc0001a6e00, {0xe90a60, 0xc000488000}, 0xc0001e6000)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 8
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x125

Error: The terraform-provider-nexus_v2.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Terraform should work

### Actual Behaviour

Plugin crashed

### Steps to Reproduce

`terraform plan`

But not sure what's specific about this blobstore group it causes to panic... Our repositories are quite huge so maybe something related to size?

**Comment by serialt** [comment]
You should use  [nexus](https://registry.terraform.io/providers/datadrivers/nexus/latest) for your project，and report issues by [github](https://github.com/datadrivers/terraform-provider-nexus/issues)
